server:
  port: 9090
spring:  servlet:    multipart:      enabled: true      max-file-size: 512MB        max-request-size: 1024MB      file-size-threshold: 1B

file-system-properties:
    location: kkuploadDir 
 
logging:  file:    name: fileUploadLog.log    